### ISSUE TITLE
How to use this library to implement instagram like horizontal recyclerview inside one of the child item of vertical recycler view

### ISSUE THREAD

**Issue by rkoshti** [alzoubiMohammed/ZExoRecyclerPlayer#2]
Let me know if it is achievable using this library

**Comment by alzoubiMohammed** [comment]
Hi @rkoshti 
Thank you for using my library.
Unfortunately, horizontal scrolling is not supported at this time.
However, it may be implemented in the next few weeks.

**Comment by rkoshti** [comment]
Thanks for the consideration. That would be great.

Also is their any plans to update this library in exo player media 3 it seems it is dependent on media 2 exoplayer which is deprecated.
@alzoubiMohammed

**Comment by rkoshti** [comment]
Any updates ? @alzoubiMohammed

**Comment by alzoubiMohammed** [comment]
Hi @rkoshti 

could you please tell me more about what you trying to implement ,so I can help you

**Comment by alzoubiMohammed** [comment]
I believe you can use the library.
In the View Holder of the vertical layout you can add horizontal recycler view and use Snap Helper to determine the video you are looking at and pass it with the same technique as in the example. 

I hope you got my point
